### ISSUE TITLE
suggest: possibility of adding a custom texture to each head

### ISSUE THREAD

**Issue by Zarkness** [AerWyn81/HeadBlocks#4]
My suggestion is to be able to put a custom texture to each head, since I would like to be able to put heads of different texture. example: to put heads with texture of Japanese lamps to match the theme of my server.

**Comment by AerWyn81** [comment]
Hi, thanks for your suggestion! 

I will put it in my idea list because currently the plugin is not necessarily designed for this use case, its main purpose being to hide a random number of heads with the same texture and it might be complex to add that, at least without thinking. I'll think about adding this feature though :)

**Comment by Zarkness** [comment]
ok, thank you very much, I hope it can be added

**Comment by AerWyn81** [comment]
This feature has been implemented and will be part of the next update!
